### ISSUE TITLE
gmaps upgrade broken

### ISSUE THREAD

**Issue by remram44** [VisTrails/VisTrails#1021]
If I let VisTrails upgrade mta-plots.vt, save and reopen, I get an InvalidPipeline. (I'm doing this on master, not using the backport)

```
Error changing version
InvalidPipeline: Pipeline has errors. Please see the detailed message for more information.
  Missing version 0 of package org.vistrails.vistrails.gmaps
  Upgrading workflow failed.
  Input port "Location" of module "GMapCell" exists, but signatures differ "(org.vistrails.vistrails.spreadsheet:CellLocation)" != "(org.vistrails.vistrails.basic:Variant)"
```

Looking at the XML, I see a GMapCell module with `version=""`.

**Comment by remram44** [comment]
It seems that the `ModuleRegistry` returns `ModuleDescriptors` with no version set (e.g. `get_descriptor_by_name()`). Should probably be fixed at that level.

**Comment by remram44** [comment]
It appears that the module registry has always done that, so I'm blaming this on the new upgrade code. It's weird that we never ran into it before.

**Comment by remram44** [comment]
Alright, @dakoop: it looks that there are confusions in the UpgradeWorkflowHandler between `version` and `package_version` on the `ModuleDescriptor`; bug is caused by [this one](https://github.com/VisTrails/VisTrails/blob/2cf6f4effd3fa183c6fd7eab47683e054e53d025/vistrails/core/upgradeworkflow.py#L780). I'm not sure what `version` is for at all?

**Comment by dakoop** [comment]
@remram44, you are correct. That kwarg to the `ModuleDescriptor` constructor should be passed as `package_version=new_pkg_version`. `version` is used with subworkflows because we allow a subworkflow (which is a vistrail) to be updated to a new version without changing its other descriptor information. Since local subworkflows live in a single package and we don't wish to bump the version number on the package (`package_version`) and have to reload the package each time, we allow subworkflow modules themselves to have version numbers to differentiate.

**Comment by remram44** [comment]
So all these `version` should be `package_version`?

**Comment by dakoop** [comment]
Yes.
