### ISSUE TITLE
annotation is not saved properly

### ISSUE THREAD

**Issue by julianafreire** [VisTrails/VisTrails#1038]
To reproduce:
1) click on a node
2) change the contents of the "Notes"
3) hit execute
When workflow is executed, the content of notes is reverted to its previous value

**Comment by remram44** [comment]
I think there should be an "about to execute" notification to let everything commit their changes before execution happens. Relying on focus-out works in most cases, but things like that can also happen.

Might not need to be 2.2.0, it only happens if changing tag or notes then executing directly (without focusing out/pressing enter).

Interestingly module parameters get committed correctly, the difference is surprising.
