### ISSUE TITLE
Update builders for 10.6->10.11

### ISSUE THREAD

**Issue by remram44** [VisTrails/VisTrails#1134]
The build machine is now 10.11 (maybe I should have thought more about that, didn't realize we were building releases on the host itself).

* the builder names are still `lion-*`
* the uploaded binary is still `*-10.6.dmg`
* we don't have a build machine for old OSX versions anymore (though Apple offers free upgrades now, we can assume people migrated)

**Comment by remram44** [comment]
On a side note, the mac build has been failing to upload to sourceforge for a while (see also #1129).

**Comment by rexissimus** [comment]
* The builders still work on the new osx version.
* Renamed the builders to 'osx'.
* Uploaded binaries are now called 'osx'. I removed '10.6' and 'intel'.
* Minimum supported version should now be 10.7, because that is the version of the currently installed testing VM. The next release should reflect this.
