### ISSUE TITLE
Workflow in /tmp can appear in workspace multiple times on OSX

### ISSUE THREAD

**Issue by remram44** [VisTrails/VisTrails#1146]
* Put VT file in /tmp/ on Mac OS X
* start "vistrails /tmp/myfile.vt"
* close VisTrails
* open it again; "myfile" is in the workspace on the left
* Command+O and open /tmp/myfile.vt: it is now twice in the workspace

![screenshot](https://cloud.githubusercontent.com/assets/426784/12627440/d2de4588-c50b-11e5-844d-94e834ee000f.png)

**Comment by remram44** [comment]
I can't reproduce this on Linux or in another folder. Is it because /tmp is a link?

**Comment by rexissimus** [comment]
You can hover the vistrail in the workspace to see the paths they refer to.

``os.path.realpath`` expands it to ``/private/tmp``. But it does not look like this is ever used in the code?

**Comment by remram44** [comment]
Adding a few `os.path.realpath()` calls in the workspace calls should fix this then?

**Comment by rexissimus** [comment]
The problem seems to be that qfiledialog resolves symlinks:
http://doc.qt.io/qt-4.8/qfiledialog.html#Option-enum
We can set the ``DontResolveSymlinks`` flag to avoid this.

I am thinking we should avoid resolving symlinks because real locations can change, have long paths, and are inflexible. The only problem is if a user uses multiple paths to refer to the same location, but I think it is a reasonable tradeoff?

**Comment by remram44** [comment]
I don't see why real locations would change more often than symlinks, and long paths are not an issue since we don't display them. I'd really rather use real paths everywhere...

**Comment by remram44** [comment]
Fixed by #1160
