### ISSUE TITLE
DownloadFile does not support URL:s longer than 250 chars

### ISSUE THREAD

**Issue by rexissimus** [VisTrails/VisTrails#1151]
It uses the encoded URL as a filename, which does not work for long URL:s.

One possibility is to truncate the filename and append the hash of the full filename. That way the filename will still be unique and somewhat readable?

Otherwise we need a different way to map the url to the filename when saving the file, like splitting the url into nested directories?

**Comment by dakoop** [comment]
Is there any reason we couldn't use only the hash of the url?

**Comment by remram44** [comment]
Since we have no mechanism to expire entries from the cache, it kind of makes sense to use some meaningful name. But really I kept the behavior from the HTTP package.

Possibilities:
* Always use a hash, like `HTTP/6b1e55cb25b2de7533ef58ca9dec128377fc0b88`
* Use a hash if the URL is longer than some limit
* Truncate the URL if longer than some limit and append hash, like `HTTP/http%3A%2Fwww.vistrails.org%2Fdownload%2Fdown_6b1e55cb25b2de7533ef58ca9dec128377fc0b88`

**Comment by rexissimus** [comment]
You may want to inspect and delete specific files in the download cache. For instance, all files from a specific domain. You could always delete all of them, but there may be situations where you do not want do do that. My solution is not a big change, and would allow you to identify at least the domain of downloaded files.

**Comment by remram44** [comment]
Yes it sound like the best solution ;) I can make the change.
