### ISSUE TITLE
URL package depends on gui

### ISSUE THREAD

**Issue by dakoop** [VisTrails/VisTrails#1202]
It would be nice to be able to use DownloadFile without the gui (e.g. in batch mode without Qt/PyQt). It looks like there is some repository stuff that uses Qt, but perhaps this could be a configuration setting that could be turned off.

**Comment by remram44** [comment]
I kept that because it was there and I don't know much about it, perhaps we can just remove that? Does it work?

The warnings can be done via `vistrails.core.debug` (which will show a graphical message if the GUI is used). `vistrails.gui.repository` only seems required to access a "cookiejar", perhaps that could be moved to configuration as well?

**Comment by dakoop** [comment]
Yep, agree on the warnings. Looking closer, I would argue `RepoSync`--the module that uses the gui resources--should be moved to its own package (named crowdlabs?), but we'll need to add cross-package upgrade logic.
