### ISSUE TITLE
Is it possible to run different python versions in different module nodes?

### ISSUE THREAD

**Issue by pedrovgp** [VisTrails/VisTrails#1228]
I have two use cases actually, one simpler than the other:

1. I am on windows. VisTrails runs python 2.7. But I have python 3.5 scripts that are already processing data. I would like to use VisTrails to bundle together these scripts and be able to audit this work(data-)flow. These scripts are mainly using pandas for data processing, so input and output are dataframes.

2. Imagine a more complex scenario, in which I have python scripts in one specific virtualenv (let's call it preparing27) which runs python 2.7 and has a given set of packges installed and it's output should than be used in a second script, which runs in a second virtualenv (say, visualize35), which runs python 3.5 and has a different set o packages installed.

I would like to be able to run a workflow similar to:
| prepare | ----> | visualize |

|prepare|: should activate preparing27, run the script and send the output to |visualize|
|visualize|: should activate visualize35, receive the the output from |prepare| as input, further process the data and generate a bunch of PDFs.

Are any of these use cases possible in VisTrails?

**Comment by remram44** [comment]
Hi @pedrovgp,

This is doable, but not directly, since VisTrails runs modules in its own Python interpreter, passing objects between them that lives in that interpreter.

You should be able to call scripts in a different environment by using [CLTools](https://www.vistrails.org/usersguide/v2.2/html/cltools.html) to call your scripts as separate programs (passing them data in/out using files or stdin/stdout).

You can also write wrapper modules that communicates with the other interpreter using some other kind of RPC. Unfortunately Python's [multiprocessing.Process](https://docs.python.org/2/library/multiprocessing.html#the-process-class), which is the easiest way to call functions in a new process, doesn't work across Python versions (and neither does pickle), so passing arbitrary objects through might get a little bit interesting (but passing CSVs or serialized numpy arrays will work fine).

**Comment by pedrovgp** [comment]
> You should be able to call scripts in a different environment by using CLTools to call your scripts as separate programs (passing them data in/out using files or stdin/stdout).

This should work. At least for managing workflows. Thanks!
