### ISSUE TITLE
Use sort_key for ports list

### ISSUE THREAD

**Issue by dakoop** [VisTrails/VisTrails#742]
Patrick Janssen suggests that a port's sort_key should be used to not only order the ports in the module box but also in the ports lists that shows up in the Module Information panel.

**Comment by rexissimus** [comment]
This has been discussed. Since the Module Information panel shows all available ports it makes more sense to keep it sorted alphabetically with used functions at the top. That way, required ports would be on top once they are set.

Visible ports are currently called "not optional". This have been used to specify required ports, but then it cannot be used as "ports that should be connected". "Optional" should be renamed to something like "visible", and a "required" flag could be used to put the port on top of the list in red to show that it needs to be set.

Also, the ports list should probably have a search box like the module palette.

**Comment by dakoop** [comment]
I agree that the naming is bad, but also note that the `min_conns` and `max_conns` are designed to cover cardinality (and thus the required vs. optional case). Thus, setting `min_conns=1` means that the module must have at least one connection/parameter to function correctly, and `min_conns=0` means the port is optional. These are not currently enforced but could be.

**Comment by remram44** [comment]
Should we display the ports with `min_conns > 0` first in the ports panel?

We could also introduce a `visible` setting and deprecate `optional` in favor of it, but that's very minor.

**Comment by rexissimus** [comment]
Good points. Yes, unset `min_conns > 0` could be shown first and marked (in red or yellow?) to show they are invalid. That would be a big improvement.

the optional/visible issue is similar to the `Constant` issue. We could probably find more of these illogical names.

**Comment by rexissimus** [comment]
#997 moves mandatory unset ports to the top and makes them bold (like they look in the pipeline view).
