### ISSUE TITLE
argparse is missing on Python 2.6

### ISSUE THREAD

**Issue by rexissimus** [VisTrails/VisTrails#877]
It is required by core.configuration. It cannot be auto-installed because installbundle imports core.configuraion.

Should we give an error, make installbundle work without configuration, or drop support for Python 2.6?

**Comment by hugovk** [comment]
Python 2.7 is now 7 years old.

## Reasons for dropping 2.6

* Unsupported since [2013-10-29](https://en.wikipedia.org/wiki/CPython#Version_history)
* https://snarky.ca/stop-using-python-2-6/
* http://www.curiousefficiency.org/posts/2015/04/stop-supporting-python26.html
* http://www.python3statement.org
* Current pip 9 deprecates Python 2.6 support, pip 10 won't support it (https://github.com/pypa/pip/issues/3955)
* Not much PyPI traffic (June 2016) https://github.com/pypa/pip/issues/3796
